# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=50)),
                ('dev_emailid', models.CharField(max_length=100)),
                ('dev_password', models.CharField(max_length=20)),
                ('dev_interest', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DevPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_info', models.CharField(max_length=1000)),
                ('post_link', models.CharField(max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev.Dev')),
            ],
        ),
    ]
