# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devpost',
            name='post_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
